analytics:
  twitter: null
  google: UA-64714395-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  lightness: 0.4446808
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#79777E'
    - '#02BB76'
    - '#000000'
    - '#B2B2B2'
  rhythmicContrast: 0.5
typography_spectrum: 0.5404255
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Soulfuel
