name: Soulfuel
favicon: null
layout_spectrum: 0.99922
typography_spectrum: 0.25274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64714395-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e01e25'
    - '#e91d25'
    - '#da1824'
    - '#df0f1f'
    - '#e51919'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
