favicon: null
name: Soulfuel
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.8
  brandStrength: 1
  lightness: 0.3829787
  brandColors:
    - '#030204'
    - '#383030'
    - '#999A9A'
    - '#D0A292'
    - '#390E05'
  rhythmicContrast: 0.5
typography_spectrum: 0.5404255
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: UA-64714395-1
  facebook: null
