name: Soulfuel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64714395-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00ff00'
    - '#4e4d4d'
    - '#6c6c6c'
    - '#8d8d8d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
